language: node_js
node_js:
  - node
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
jobs:
  include:
    - stage: test
      script: npm run coveralls
    - stage: npm release
      if: tag IS present
      node_js: "10"
      deploy:
        provider: npm
        skip_cleanup: true
        email: johan@lindell.me
        api_key: $NPM_TOKEN
        on:
          all_branches: true
env:
  global:
    secure: xPqK82e3Fak0vxfXZ/jDZMG9jRDgU/qd2BQtno92HxBjgrnYiS5igaSf1s6geraXDrMAf1hO8ZsPf/TveZ+zyO2BKbXO0YWn1B2U7lxsVU7HATFyQt+JNZSxnplfljekKBme2hMXlpn7ffmmxohUKLQN8LVIx7Sm8TaXINrr2Xj77dyU/kI5WqJM583Aj63YXq6PM5PEGtUblrbChYGtnrXZL6fpaezhdTd9k9u/ElHD1JIgh2lwOvLW5C+HxjUGOG6TDdeqRLmXjMXSgNV/iuN/8lXnsZd5AcqcrAiUxljsCiAIIW+sDNWIbe6cfn22E35XLn5dIiI67iHAWqc+HGVxS8gf0OVSk8cfNAYdcZ8fiLUntkAdA/yMgQl6G3s1/9+JF/ZBtJdGDSvI3lJwTQs1PMB9rWx1DmOxUqJMEfcC2N40dW+Jbmba4R/GWvD2pUE2upffBerSRzlWsanPetgy4Pjwz9mNLmb1H+bknMQcyxe16g9yreGeUd44GTi9W3uSHBMGTraBK8G5Lg6kiq9jw1fXN1Hkjj2uWyhpZd5uesVpNHO9RcfuTMgC0NeEBdfB+vdq5pufG6RZYKaZX1NflvSyuzPMpBI52zrpW7DW36Lh+MdILwGiQU+mb/W4Th3YRGA9+wtgNkWa7UXU+7j8R6VTmELBmCQioqHMsFg=
